name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check Secrets
        run: |
          echo "Checking Secrets..."
          echo "EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}"
          echo "HOST_DNS: ${{ secrets.HOST_DNS }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"